version: "3"
services:
  app:
    image: stikinote-frontend:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/node_modules/
      - /usr/src/.next/
    environment:
      # - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
