version: "3"
services:
  app:
    image: stikinote-frontend:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
      - /usr/src/app/.next/
      - .next/cache/images:/usr/src/app/.next/cache/images
    environment:
      # - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
